# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

import Grapher
from Solver import MasonSolver, sympify


class Ui_MainWindow(object):
    def __init__(self):
        self.G = None
        self.source = None
        self.destination = None
        self.solver = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 894)
        MainWindow.setStyleSheet("background-color:  rgb(237, 246, 255);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(70, 0, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)

        self.noNodes = QtWidgets.QSpinBox(self.centralwidget)
        self.noNodes.setGeometry(QtCore.QRect(20, 170, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(22)
        self.noNodes.setFont(font)
        self.noNodes.setStyleSheet("background-color: ghostWhite;")

        self.titlelLine = QtWidgets.QFrame(self.centralwidget)
        self.titlelLine.setGeometry(QtCore.QRect(0, 90, 611, 16))
        self.titlelLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titlelLine.setLineWidth(3)
        self.titlelLine.setFrameShape(QtWidgets.QFrame.HLine)

        self.noNodesLabel = QtWidgets.QLabel(self.centralwidget)
        self.noNodesLabel.setGeometry(QtCore.QRect(20, 110, 251, 51))

        self.enterGraph = QtWidgets.QPushButton(self.centralwidget)
        self.enterGraph.setGeometry(QtCore.QRect(390, 130, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(24)
        self.enterGraph.setFont(font)
        self.enterGraph.setStyleSheet("background-color: rgb(0, 100, 125);\n"
                                      "color: ghostWhite;")
        self.enterGraph.clicked.connect(self.showGraph)

        self.calculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(390, 240, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(24)
        self.calculateButton.setFont(font)
        self.calculateButton.setStyleSheet("background-color: rgb(0, 100, 125);\n"
                                           "color: ghostWhite;")
        self.calculateButton.clicked.connect(self.calculate)

        self.solutionLine = QtWidgets.QFrame(self.centralwidget)
        self.solutionLine.setGeometry(QtCore.QRect(0, 330, 611, 20))
        self.solutionLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.solutionLine.setLineWidth(2)
        self.solutionLine.setFrameShape(QtWidgets.QFrame.HLine)

        self.end = QtWidgets.QSpinBox(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(210, 270, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(22)
        self.end.setFont(font)
        self.end.setStyleSheet("background-color: ghostWhite;")

        self.start = QtWidgets.QSpinBox(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(20, 270, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(22)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color: ghostWhite;")

        self.end_label = QtWidgets.QLabel(self.centralwidget)
        self.end_label.setGeometry(QtCore.QRect(200, 220, 121, 51))

        self.start_label = QtWidgets.QLabel(self.centralwidget)
        self.start_label.setGeometry(QtCore.QRect(20, 220, 151, 51))

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 340, 612, 540))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 610, 538))

        content_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)

        self.solution = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.solution.setGeometry(10, 10, 10, 10)
        self.solution.setAlignment(Qt.AlignTop | Qt.AlignLeft)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        content_layout.addWidget(self.solution)

        self.start_label.raise_()
        self.title.raise_()
        self.noNodes.raise_()
        self.titlelLine.raise_()
        self.noNodesLabel.raise_()
        self.enterGraph.raise_()
        self.calculateButton.raise_()
        self.solutionLine.raise_()
        self.end.raise_()
        self.start.raise_()
        self.end_label.raise_()
        self.scrollArea.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showGraph(self):
        self.G = Grapher.run(int(self.noNodes.value()))

    def calculate(self):
        print(f'{type(self.start.value())}: {self.start.value()}')
        self.solver = MasonSolver(self.G.graph.adj_list, str(self.start.value()), str(self.end.value()))
        print(self.G.graph.adj_list)
        self.formateOutput()

    def formateOutput(self):
        font_content = QtGui.QFont()
        font_content.setFamily("Microsoft New Tai Lue")
        font_content.setPointSize(18)

        solution = '<span style="font-weight: bold; color: #551712; font-size: 22pt; font-family: Microsoft New ' \
                   'Tai Lue;">Solution:</span><br>'

        # Overall transfer function title
        solution += '<span style="font-weight: bold; color: #293241; font-size: 20pt; font-family: Microsoft New Tai ' \
                    'Lue;">Overall transfer function: </span>'
        solution += str(self.solver.calculate_transferFunction()) + '<br>'

        # System delta title
        solution += '<span style="font-weight: bold; color: #293241; font-size: 20pt; font-family: Microsoft New Tai ' \
                    'Lue;">System Delta: </span>'

        solution += str(self.solver.delta) + '<br>'

        # Forward paths title
        solution += '<span style="font-weight: bold; color: #293241; font-size: 20pt; font-family: Microsoft New Tai ' \
                    'Lue;">Forward paths:</span><br>'
        for i in range(0, len(self.solver.forwardPaths)):
            solution += f'P{i + 1}: {self.solver.forwardPaths[i].trace()}<br>' \
                        f'<tab>&nbsp;&nbsp;&nbsp;&nbsp;Gain: {self.solver.forwardPaths[i].gain} = {sympify(self.solver.forwardPaths[i].gain)}<br>' \
                        f'<tab>&nbsp;&nbsp;&nbsp;&nbsp;Δ{i + 1}: {self.solver.forwardPaths[i].delta} = {sympify(self.solver.forwardPaths[i].delta)}<br>'

        # Loops title
        solution += '<span style="font-weight: bold; color: #293241; font-size: 20pt; font-family: Microsoft New Tai ' \
                    'Lue;">Loops:</span><br>'
        for i in range(0, len(self.solver.loops)):
            solution += f'L{i + 1}: {self.solver.loops[i].trace()}<br>' \
                        f'<tab>&nbsp;&nbsp;&nbsp;&nbsp;Gain:   {self.solver.loops[i].gain} = {sympify(self.solver.loops[i].gain)}<br>'

        # Non-touching loops title
        solution += '<span style="font-weight: bold; color: #293241; font-size: 20pt; font-family: Microsoft New Tai ' \
                    'Lue;">Non-touching loops:</span><br>'
        for group in self.solver.nonTouching_loops:
            for loop in group:
                print(loop.trace(), end=" ")
            print()
        for key, value in self.solver.nonTouching_loops_map.items():
            solution += key + ': ' + value + '\n'

        self.solution.setFont(font_content)
        self.solution.setHtml(solution)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SignalFlowGraphSolver"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" "
                                                    "font-size:36pt; font-weight:600; font-style:italic; "
                                                    "color:#414141; vertical-align:sub;\">Signal Flow Graph "
                                                    "Solver</span></p></body></html>"))
        self.noNodesLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:23pt; "
                                                           "color:#414141;\">Number of "
                                                           "Nodes</span></p></body></html>"))
        self.enterGraph.setText(_translate("MainWindow", "Enter Graph"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))
        self.end_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; "
                                                        "color:#414141;\">End Node</span></p></body></html>"))
        self.start_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; "
                                                          "color:#414141;\">Start Node</span></p></body></html>"))
        self.solution.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; "
                                                       "color:#414141;\">Solution "
                                                       "here</span></p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
