# -*- coding: utf-8 -*-
import os
from subprocess import call

# Form implementation generated from reading ui file 'Control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def __init__(self):
        self.G = None
        self.solutionLine = None
        self.calculate = None
        self.titlelLine = None
        self.enterGraph = None
        self.NoNodes = None
        self.centralwidget = None
        self.title = None
        self.noNodesLabel = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 839)
        MainWindow.setStyleSheet("background-color:  rgb(204, 217, 221);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(70, 0, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setObjectName("title")

        self.NoNodes = QtWidgets.QSpinBox(self.centralwidget)
        self.NoNodes.setGeometry(QtCore.QRect(320, 130, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(22)
        self.NoNodes.setFont(font)
        self.NoNodes.setStyleSheet("background-color: ghostWhite;")
        self.NoNodes.setObjectName("NoNodes")

        self.titlelLine = QtWidgets.QFrame(self.centralwidget)
        self.titlelLine.setGeometry(QtCore.QRect(0, 90, 611, 16))
        self.titlelLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titlelLine.setLineWidth(3)
        self.titlelLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.titlelLine.setObjectName("titleLine")

        self.noNodesLabel = QtWidgets.QLabel(self.centralwidget)
        self.noNodesLabel.setGeometry(QtCore.QRect(20, 140, 261, 51))
        self.noNodesLabel.setObjectName("noNodesLabel")

        self.enterGraph = QtWidgets.QPushButton(self.centralwidget)
        self.enterGraph.setGeometry(QtCore.QRect(20, 220, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(24)
        self.enterGraph.setFont(font)
        self.enterGraph.setStyleSheet("background-color: rgb(0, 100, 125);\n"
                                      "color: ghostWhite;")
        self.enterGraph.setObjectName("enterGraph")
        self.enterGraph.clicked.connect(self.showGraph)

        self.calculate = QtWidgets.QPushButton(self.centralwidget)
        self.calculate.setGeometry(QtCore.QRect(380, 220, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(24)
        self.calculate.setFont(font)
        self.calculate.setStyleSheet("background-color: rgb(0, 100, 125);\n"
                                     "color: ghostWhite;")
        self.calculate.setObjectName("calculate")

        self.solutionLine = QtWidgets.QFrame(self.centralwidget)
        self.solutionLine.setGeometry(QtCore.QRect(0, 330, 611, 20))
        self.solutionLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.solutionLine.setLineWidth(2)
        self.solutionLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.solutionLine.setObjectName("solutionLine")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showGraph(self):
        from Grapher import Grapher
        self.G = Grapher.G

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SignalFlowGraphSolver"))
        self.title.setText(_translate("MainWindow",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; "
                                      "font-weight:600; font-style:italic; color:#414141; "
                                      "vertical-align:sub;\">Signal Flow Graph Solver</span></p></body></html>"))
        self.noNodesLabel.setText(_translate("MainWindow",
                                             "<html><head/><body><p><span style=\" font-size:24pt; "
                                             "color:#414141;\">Number of Nodes</span></p></body></html>"))
        self.enterGraph.setText(_translate("MainWindow", "Enter Graph"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
